// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NzX9yGkUcTCCvleE5coWBKMjajDxxbM',
    appId: '1:604609230277:web:f3615d492883b2348207ac',
    messagingSenderId: '604609230277',
    projectId: 'liris-s2',
    authDomain: 'liris-s2.firebaseapp.com',
    storageBucket: 'liris-s2.firebasestorage.app',
    measurementId: 'G-HHDGS86Y0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOuM3toTPjgHgxfaHVmcYV1B99PL6-POs',
    appId: '1:604609230277:android:ce514be46f7f60608207ac',
    messagingSenderId: '604609230277',
    projectId: 'liris-s2',
    storageBucket: 'liris-s2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWKjO0NfP1226D3tv_TRTIp8UrIre5Ys',
    appId: '1:604609230277:ios:c44202ee117529598207ac',
    messagingSenderId: '604609230277',
    projectId: 'liris-s2',
    storageBucket: 'liris-s2.firebasestorage.app',
    iosBundleId: 'com.example.lirisWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWKjO0NfP1226D3tv_TRTIp8UrIre5Ys',
    appId: '1:604609230277:ios:c44202ee117529598207ac',
    messagingSenderId: '604609230277',
    projectId: 'liris-s2',
    storageBucket: 'liris-s2.firebasestorage.app',
    iosBundleId: 'com.example.lirisWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7NzX9yGkUcTCCvleE5coWBKMjajDxxbM',
    appId: '1:604609230277:web:20729aba0a2ad3bf8207ac',
    messagingSenderId: '604609230277',
    projectId: 'liris-s2',
    authDomain: 'liris-s2.firebaseapp.com',
    storageBucket: 'liris-s2.firebasestorage.app',
    measurementId: 'G-TDQ822Z9MF',
  );

}